In [44]:
import pandas as pd

In [45]:
# Espacio muestral
sample_space = pd.DataFrame(
    {
        y: {
            x: f"[{x} , {y}]" for x in range(1, 7)
        } for y in range(1, 7)
    }
)

# Condicional si X y Y son pares
def xy_are_pair(x: int, y: int):
    if (x % 2 == 0 and y % 2 == 0):
        return "background-color: #000000; color: #35FF80"
    else:
        return "background-color: #000000; color: #134E29"

# Condicional para Y reduciendo el espacio muestral
def y_is_pair(y: int):
    if y % 2 == 0:
        return "background-color: #000000; color: #134E29"
    else:
        return "background-color: #272727; color: #404040"

# Condicional para X dado Y
def x_is_pair_after_y(x, y):
    if (x % 2 == 0 and y % 2 == 0):
        return "background-color: #000000; color: #35FF80"
    elif y % 2 == 0:
        return "background-color: #000000; color: #134E29"
    else:
        return "background-color: #272727; color: #404040"

# Condicional para Y si es par
def y_is_pair_complete(y: int):
    if y % 2 == 0:
        return "background-color: #000000; color: #35FF80"
    else:
        return "background-color: #000000; color: #404040"


# Estilización inicial
def init_style(df: pd.DataFrame):
    return pd.DataFrame(
        {
            y: {
                x: "background-color: #272727; color: white" for x in range(1, 7)
            } for y in range(1, 7)
        }
    )

# Estilización de X y Y pares
def xy_pair(df: pd.DataFrame):
    return pd.DataFrame(
        {
            y: {
                x: xy_are_pair(x, y) for x in range(1, 7)
            } for y in range(1, 7)
        }
    )

# Estilización de reducción del espacio muestral en Y
def y_pair(df: pd.DataFrame):
    return pd.DataFrame(
        {
            y: {
                x: y_is_pair(y) for x in range(1, 7)
            } for y in range(1, 7)
        }
    )

# Estilización de X dado Y
def x_after_y(df: pd.DataFrame):
    return pd.DataFrame(
        {
            y: {
                x: x_is_pair_after_y(x, y) for x in range(1, 7)
            } for y in range(1, 7)
        }
    )

# Estilización para X si es par
def y_pair_complete(df: pd.DataFrame):
    return pd.DataFrame(
        {
            y: {
                x: y_is_pair_complete(y) for x in range(1, 7)
            } for y in range(1, 7)
        }
    )

# Tipos de probabilidad

Con frecuencia, cuando se estudia probabilidad, estos diferentes tipos de probabilidad generan mucha confusión, por eso es muy importante tener esto claro además porque, debido a que la probabilidad en sí misma es la cuantificación de la incertidumbre y la incertidumbre en sí misma es la toma de decisiones con información incompleta, a menudo cuando estamos tomando decisiones en una situación con información incompleta puede ocurrir que aparezca información nueva que genere un cambio de las probabilidades. Y ese tipo de situaciones tiene que cuantificarse con otros conceptos adicionales sobre el concepto de probabilidad básico.

De esta manera, tenemos tres tipos de probabilidad a definir:

- Conjunta
- Marginal
- Condicional

Como estos conceptos suelen ser algo abstractos cuando se estudian por primera vez, es mejor entenderlos a través de un ejemplo visual. Usemos el juego de lanzar dos dados y vamos a estudiar el espacio muestral.

Tenemos esta matriz en donde filas y columnas representan todos los posibles estados tanto del primer como del segundo dado. Entonces tenemos un espacio muestral gigantesco de 36 combinaciones. Identifiquemos estas diferentes probabilidades y cuáles son sus interpretaciones.

In [46]:
sample_space.style.apply(init_style, axis= None)

### Probabilidad conjunta

Vamos a formularnos la siguiente pregunta: ¿Cuál es la probabilidad de que ambos números caigan en número par?

Considerando el espacio muestral de los dos dados y sus 36 posibilidades, responder a esta pregunta es bastante sencillo.

Esta probabilidad se calcula con el conteo en donde el resultado de ambos dados es par:

In [47]:
sample_space.style.apply(xy_pair, axis= None)

Entendiendo que los sucesos exitosos son 9 y nuestro espacio muestral tiene en total 36 posibles ocurrencias, definimos entonces que:
$$P(A = par,B = par) = \frac{9}{36}$$

Simplificando la expresión también corresponde al valor $\frac{1}{4}$:

$$P(A = par,B = par) = \frac{9}{36} = \frac{1}{4}$$

Si lo vemos a mayor detalle, esto es la unión de dos sucesos en los que $A$ resulta en par y $B$ también, es decir, son dos sucesos **separados** y cuando calculamos la probabilidad de 2 o más sucesos a esto se le llama una probabilidad **conjunta**.

### Probabilidad condicional

Ahora consideremos la siguiente pregunta: ¿Cuál es la probabilidad de que $A$ caiga en par, sabiendo que $B$ ya cayó en par?

Nótese que esta pregunta es ligeramente distinta a la anterior: supone una condición previa. Esa condición previa impone una condición sobre el espacio muestral que será la siguiente, resaltada en color negro:

In [48]:
sample_space.style.apply(y_pair, axis= None)

Ahora sólo tenemos que considerar las situaciones en las que $B$ es par, que ahora pasan a ser sólo 18 posibles ocurrencias.

Esta probabilidad la vamos a formular de la siguiente manera:

$$ P(A = par | B = par) $$

Esto se lee como "La probabilidad de que $A$ sea par dado que $B$ es par".

Como esto impone una condición previa, a este tipo de probabilidades las llamamos **condicionales**. Habiendo restringido ya el espacio muestral, el conteo de éxitos en $A$ sólo va a considerar el espacio restringido:

In [49]:
sample_space.style.apply(x_after_y, axis= None)

Podemos observar que, en comparación con el ejemplo de probabilidad conjunta, el número de eventos exitosos **no cambió**. Lo que cambió fue el número de eventos posibles y esto modifica que ya no tenemos 9 de 36 sino 9 de 18:

$$ P(A=par | B=par) = \frac{9}{18} $$

### Relación entre la probabilidad conjunta y la probabilidad condicional

¿Cómo están relacionados los dos ejemplos de los puntos anteriores? Resulta que también podemos formularnos la siguiente pregunta: ¿Cuál es la probabilidad de que $B$ caiga en par?

$$ P(B=par)$$

Y entonces aquí tenemos que esto es una probabilidad que no impone ninguna condición, es decir, es un suceso simple. En esta probabilidad podemos utilizar todo el espacio muestral. Entonces, de la misma manera tenemos 36 posibles ocurrencias de las cuales 18 cuentan como éxitos.

In [50]:
sample_space.style.apply(y_pair_complete, axis= None)

Entonces podemos decir que la probabilidad de que B sea par es de 18 en 36:

$$ P(B=par) = \frac{18}{36} $$

Y en todo esto, ¿Cuál es la relación? Claro, son tres probabilidades que corresponden a probabilidades diferentes pero resulta que si tomamos los ejemplos de probabilidad condicional y el suceso simple que justamente acabamos de ver, veremos qué resulta:

$$ \text{Probabilidad condicional: }P(A=par | B=par) = \frac{9}{18} $$
$$ \text{Suceso simple: }P(B=par) = \frac{18}{36} $$

$$ \frac{9}{18} * \frac{18}{36} = \frac{9}{36} $$

Podemos darnos cuenta que, el producto de estas dos probabilidades nos da como resultado $\frac{9}{36}$ lo que también viene siendo $\frac{1}{4}$, es decir, esto nos da exactamente la probabilidad conjunta del primer ejemplo.

Entonces podríamos decir entonces que la probabilidad conjunta de que suceda $A$ y $B$ es igual a la probabilidad condicional de que suceda $A$ dado que ya sabemos que sucedió $B$ por la probabilidad de que suceda $B$:

$$ P(A,B) = P(A|B) \text{ } P(B) $$

Esto no corresponde a este caso en particular sino que es una regla general que se llama **La regla del producto** y es una regla que se usa para descomponer en general probabilidades condicionales. Y como te darás cuenta, no estamos demostrando la regla como tal sino que estamos simplemente analizando un hecho en el cual vemos que esta regla es evidente.

Es así como entendemos que las probabilidades conjuntas se relacionan con una probabilidad condicional multiplicado por una probabilidad sencilla que no implica ninguna condición.

Esta regla general es esencial y la estaremos utilizando en muchas situaciones.

### Probabilidad marginal

¿A qué correspondería una probabilidad marginal? ¿Qué quiere decir *marginal*? Marginal es cuando obtenemos una probabilidad sencilla a partir de una probabilidad conjunta, es decir, volviendo al ejemplo de la probabilidad conjunta $P(A,B)$ sólo queremos conocer la probabilidad del primer suceso que es $A$, independientemente de lo que suceda con $B$. Así, eso se define como la suma de todas las probabilidades conjuntas sobre los demás estados que no están considerando a $A$

$$ P(A) = \sum_{b} P(A,B) $$

Para calcular la probabilidad marginal de A, necesitamos sumar todas las probabilidades conjuntas en las que A ocurra, sin importar el valor de B lo que nos da la probabilidad de A al considerar todas las posibles combinaciones de B. Es útil cuando queremos estudiar la probabilidad de un evento individual sin tener en cuenta otros eventos que puedan estar ocurriendo simultáneamente.

$$ P(A=par) = \sum_{b} P(A,B) = \frac{18}{36} = \frac{1}{2} $$

donde $\sum_{b}$ representa la suma de todos los posibles resultados de $B$.

Esta probabilidad $P(A=par)$ es exactamente el mismo tipo de probabilidad sencilla de B en $P(A,B) = P(A|B)\text{ }P(B)$, es decir, $P(B)$

De esta manera podemos ver que la probabilidad conjunta por la probabilidad marginal de una variable nos da como resultado la probabilidad marginal de la otra variable:

$$P(A,B) = P(A|B)\text{ }P(B)$$
$$P(B,A) = P(B|A)\text{ }P(A)$$

Podemos ver que la definición se vuelve cíclica. Veremos libros de estadística en los que definen la probabilidad marginal en términos de la conjunta y la condicional y la condicional en términos de la conjunta y la marginal, etc. pero la relación fundamental va a ser siempre esta regla del producto.